apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cryptorec-tls
  namespace: cryptorec
spec:
  secretName: cryptorec-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Your Organization
  commonName: cryptorec.rndv-testing.xyz
  dnsNames:
    - cryptorec.rndv-testing.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
